#!/usr/bin/env python3
"""The Kinas logo, from one source image to the two places it appears.

    python3 scripts/logo.py [new-logo.png]

With an argument, the image replaces app/src-tauri/icons/source/kinas-logo.png first. Then:

1. app/src-tauri/icons/source/app-icon.png: the logo on a navy rounded square, 824 px of artwork on a 1024 px canvas
   (macOS's icon grid; a rounded square, so macOS 26 does not set the icon on a grey tile). Regenerate the app's icon
   set from it, then delete the android/ and ios/ folders the generator adds (the app is macOS only):

       app/node_modules/.bin/tauri icon app/src-tauri/icons/source/app-icon.png -o app/src-tauri/icons

2. packages/commands/src/logo-grid.ts: the logo as a 44x44 grid, which the CLI draws in braille.

The source is square pixel art on a 16 px grid with transparent corners. Needs Pillow.
"""

import json
import shutil
import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "app/src-tauri/icons/source/kinas-logo.png"
APP_ICON = ROOT / "app/src-tauri/icons/source/app-icon.png"
GRID_TS = ROOT / "packages/commands/src/logo-grid.ts"
NAVY = (10, 20, 32, 255)
CELL = 16


def app_icon(logo: Image.Image) -> Image.Image:
    tile = Image.new("RGBA", (824, 824), (0, 0, 0, 0))
    ImageDraw.Draw(tile).rounded_rectangle([0, 0, 823, 823], radius=185, fill=NAVY)
    tile.alpha_composite(logo.resize((760, 760), Image.LANCZOS), (32, 32))
    canvas = Image.new("RGBA", (1024, 1024), (0, 0, 0, 0))
    canvas.alpha_composite(tile, (100, 100))
    return canvas


def grid(logo: Image.Image) -> list[str]:
    """44x44 rows: "#" a warm-white pixel, "." the navy disc, " " outside it."""
    n = logo.size[0] // CELL

    def cell(x: int, y: int) -> str:
        r, g, b, a = logo.getpixel((x * CELL + CELL // 2, y * CELL + CELL // 2))
        return " " if a < 128 else ("#" if r + g + b > 600 else ".")

    full = [[cell(x, y) for x in range(n)] for y in range(n)]
    rows = []
    for y in range(n // 2):
        row = ""
        for x in range(n // 2):
            block = [full[y * 2 + dy][x * 2 + dx] for dy in (0, 1) for dx in (0, 1)]
            # Any warm-white pixel keeps its dot: under a majority rule the dithered bust would disappear.
            row += "#" if "#" in block else ("." if sum(c != " " for c in block) >= 2 else " ")
        rows.append(row)
    return rows


def main() -> None:
    if len(sys.argv) > 1:
        shutil.copyfile(sys.argv[1], SOURCE)
    logo = Image.open(SOURCE).convert("RGBA")
    width, height = logo.size
    if width != height or width % (CELL * 2):
        sys.exit(f"{SOURCE}: expected a square image on a {CELL} px grid, got {width}x{height}")

    app_icon(logo).save(APP_ICON)
    rows = grid(logo)
    body = "\n".join(f"  {json.dumps(r)}," for r in rows)
    GRID_TS.write_text(
        "// Generated by scripts/logo.py from app/src-tauri/icons/source/kinas-logo.png — do not edit by hand.\n"
        f'// {len(rows)}x{len(rows)}: "#" a warm-white pixel, "." the navy disc, " " outside it.\n'
        f"export const LOGO_GRID: readonly string[] = [\n{body}\n];\n"
    )
    print(f"wrote {APP_ICON.relative_to(ROOT)} and {GRID_TS.relative_to(ROOT)} ({len(rows)}x{len(rows)})")


if __name__ == "__main__":
    main()
